apiVersion: batch/v1
kind: Job
metadata:
  generateName: database-migration-
  annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: dummy
        image: alpine
        command:
          - "sleep"
          - "5"
      restartPolicy: Never
  backoffLimit: 2
