apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-slack-notification-
  annotations:
      argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy
        image: alpine
        command:
          - "sleep"
          - "5"
      restartPolicy: Never
  backoffLimit: 2
