apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: cluster-dev
      - env: prod
        cluster: in-cluster
  template:
    metadata:
      name: '{{env}}-common-app'
      namespace: argocd
    spec:
      project: default
      destination:
        server: '{{cluster}}'
        namespace: default
      source:
        path: apps/dumb
        repoURL: https://github.com/felipelaptrin/argocd-blog.git
        targetRevision: feat/generator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true