apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-dev
  namespace: argocd
stringData:
  config: |
    {
      "bearerToken": "TOKEN",
      "tlsClientConfig": {
        "insecure":false,
        "caData":"CERTIFICATE"
      }
    }
  name: cluster-dev
  server: https://cluster-dev-control-plane:6443
