apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-deployment
  labels:
    app: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
    spec:
      containers:
      - name: common
        image: nginx:latest