apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-applications
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd-apps/applications/dev
    repoURL: git@github.com:felipelaptrin/argocd-blog.git
    targetRevision: feat/app-of-apps
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true