apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/applications
    repoURL: git@github.com:felipelaptrin/argocd-blog.git
    targetRevision: feat/app-of-apps
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true