apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app-of-apps-applications
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/applications
    repoURL: https://github.com/felipelaptrin/argocd-blog.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true