apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-dummy-with-hooks-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: apps/dummy
    repoURL: https://github.com/felipelaptrin/argocd-blog.git
    targetRevision: feat/hooks
  project: default
